=== GreenTeilor/JAVA_Courses_teachmeskills/data/xml/data2.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="stringtype">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="inttype">
        <xs:restriction base="xs:positiveInteger"/>
    </xs:simpleType>

    <xs:complexType name="employeetype">
        <xs:sequence>
            <xs:element name="name" type="stringtype"/>
            <xs:element name="lastName" type="stringtype"/>
            <xs:element name="patronymic" type="stringtype"/>
            <xs:element name="position" type="stringtype"/>
            <xs:element name="department" type="stringtype"/>
            <xs:element name="workExperience" type="inttype"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="employeestype">
        <xs:sequence>
            <xs:element name="employee" maxOccurs="unbounded" type="employeetype"/>
        </xs:sequence>
        <xs:attribute name="facility" type="stringtype" use="required"/>
    </xs:complexType>

    <xs:element name="employees" type="employeestype"/>
</xs:schema>

=== GreenTeilor/JAVA_Courses_teachmeskills/data/xml/data.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE employees SYSTEM "format.dtd">
<employees facility="clinic"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="data2.xsd">
    <employee>
        <name>Ivan</name>
        <lastName>Ivanov</lastName>
        <patronymic>Ivanovich</patronymic>
        <position>surgeon</position>
        <department>surgery</department>
        <workExperience>20</workExperience>
    </employee>
    <employee>
        <name>Natalya</name>
        <lastName>Ivanova</lastName>
        <patronymic>Igorevna</patronymic>
        <position>nurse</position>
        <department>ambulance</department>
        <workExperience>25</workExperience>
    </employee>
</employees>
